apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svgtopng-ingress
  labels:
    app: svgtopng
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: svgtopng.doodl.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svgtopng-service
            port:
              number: 80
  tls:
  - hosts:
    - svgtopng.doodl.ai
    secretName: svgtopng-tls
